ls:
  .dir: lowercase
  .scss: lowercase
  .ts: lowercase
  backend/src/data/migrations:
    .ts: snake_case


ignore:
    - node_modules
    - build
    - shared/build
    - shared/node_modules
    - frontend/build
    - frontend/node_modules
    - backend/build
    - backend/node_modules
    - .git
