const MILLISECONDS_IN_SECOND = 1000;
const MAX_RATE_STEP_ANGLE_IN_DEGREES = 45;
const MIDDLE_RATE_STEP = 1;
const RATE_STEPS = ['0.25', '0.5', '0.75', '1.0', '1.25', '1.5', '1.75'];

export {
  MILLISECONDS_IN_SECOND,
  MAX_RATE_STEP_ANGLE_IN_DEGREES,
  MIDDLE_RATE_STEP,
  RATE_STEPS,
};
