const ARRAY_SHIFT = 1;
const FIRST_ITEM_IN_ARRAY = 0;
const MILLISECONDS_IN_SECOND = 1000;
const DEFAULT_SKIP_TIME = 15000;
const MAX_RATE_STEP_ANGLE_IN_DEGREES = 45;
const MIDDLE_RATE_STEP_ANGLE_IN_DEGREES = 0;

export {
  ARRAY_SHIFT,
  FIRST_ITEM_IN_ARRAY,
  MILLISECONDS_IN_SECOND,
  DEFAULT_SKIP_TIME,
  MAX_RATE_STEP_ANGLE_IN_DEGREES,
  MIDDLE_RATE_STEP_ANGLE_IN_DEGREES,
};
