const ARRAY_SHIFT = 1;
const MILLISECONDS_IN_SECOND = 1000;
const DEFAULT_START_TIME = 0;
const DEFAULT_SKIP_TIME = 15000;
const DEFAULT_CURRENT_TIME = 0;
const MAX_RATE_STEP_ANGLE_IN_DEGREES = 45;
const MIDDLE_RATE_STEP_ANGLE_IN_DEGREES = 0;
const DEFAULT_DURATION = 0;

export {
  ARRAY_SHIFT,
  MILLISECONDS_IN_SECOND,
  DEFAULT_START_TIME,
  DEFAULT_SKIP_TIME,
  DEFAULT_CURRENT_TIME,
  MAX_RATE_STEP_ANGLE_IN_DEGREES,
  MIDDLE_RATE_STEP_ANGLE_IN_DEGREES,
  DEFAULT_DURATION,
};
