enum EpisodeValidationRule {
  EPISODE_NAME_MIN_LENGTH = 1,
  EPISODE_NAME_MAX_LENGTH = 20,
  EPISODE_DESCRIPTION_MIN_LENGTH = 10,
  EPISODE_DESCRIPTION_MAX_LENGTH = 200,
}

export { EpisodeValidationRule };
