enum PodcastValidationRule {
  PODCAST_NAME_MIN_LENGTH = 1,
  PODCAST_NAME_MAX_LENGTH = 20,
  PODCAST_DESCRIPTION_MIN_LENGTH = 15,
  PODCAST_DESCRIPTION_MAX_LENGTH = 100,
}

export { PodcastValidationRule };
