enum PodcastValidationRule {
  PODCAST_NAME_MIN_LENGTH = 1,
  PODCAST_NAME_MAX_LENGTH = 25,
  PODCAST_DESCRIPTION_MIN_LENGTH = 5,
  PODCAST_DESCRIPTION_MAX_LENGTH = 200,
}

export { PodcastValidationRule };
