enum UserValidationRule {
  FIRST_NAME_MIN_LENGTH = 1,
  FIRST_NAME_MAX_LENGTH = 20,
  LAST_NAME_MIN_LENGTH = 1,
  LAST_NAME_MAX_LENGTH = 20,
  NICKNAME_MIN_LENGTH = 3,
  NICKNAME_MAX_LENGTH = 15,
  PASSWORD_MIN_LENGTH = 6,
  PASSWORD_MAX_LENGTH = 15,
  BIO_MAX_LENGTH = 256,
}

export { UserValidationRule };
