const DEFAULT_EPISODE_PAGE = 1;
const DEFAULT_EPISODE_ROW = 5;

const DEFAULT_EPISODE_PAGINATION = {
  page: DEFAULT_EPISODE_PAGE,
  row: DEFAULT_EPISODE_ROW,
};

export {
  DEFAULT_EPISODE_PAGINATION,
  DEFAULT_EPISODE_PAGE,
};
