const DEFAULT_EPISODE_PAGE = 0;
const DEFAULT_EPISODE_ROW = 5;

const DEFAULT_EPISODE_PAGINATION = {
  page: DEFAULT_EPISODE_PAGE,
  row: DEFAULT_EPISODE_ROW,
};

const ROW_COUNT = [5, 10, 20];

export {
  DEFAULT_EPISODE_PAGINATION,
  DEFAULT_EPISODE_PAGE,
  ROW_COUNT,
};
