name: Deployment

env:
  NODE_VERSION: 14

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Deployment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_OWNER_EMAIL }}

      # - name: Slack Notification
      #   if: always()
      #   uses: rtCamp/action-slack-notify@v2.2.0
      #   env:
      #     SLACK_ICON_EMOJI: ':bell:'
      #     SLACK_USERNAME: Deployment
      #     SLACK_TITLE: Status
      #     SLACK_MESSAGE: ${{ job.status == 'success' && 'Success 🟢' || job.status == 'cancelled' && 'Cancelled 🟡' || 'Error 🔴' }}
      #     SLACK_COLOR: ${{ job.status }}
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
